# iTwin.js Core CI Build

trigger:
  branches:
    include:
      - ui/new-ci-job
  paths:
    exclude:
      - ui

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - ui/new-ci-job
  paths:
    exclude:
      - ui

jobs:
  - template: ci-core.yaml
    parameters:
      name: Node_16
      nodeVersion: 16.13.0
      pool:
        name: $(name)
        demands:
          - Agent.OS -equals $(platform)
