# iTwin.js Helgrind Testing

trigger: none
pr: none
schedules:
  - cron: "0 5 * * Sat"
    displayName: Weekly Saturday Helgrind Testing
    branches:
      include:
        - master
    always: false

jobs:
  - job:
    timeoutInMinutes: 180
    pool:
      name: iModelTechCI
      demands:
      - Agent.OS -equals Linux
    variables:
      HELGRIND_RESULTS: $(Build.StagingDirectory)/helgrind-results/
    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true

      - task: NodeTool@0
        displayName: "Use Node 16"
        inputs:
          versionSpec: 16.15.0
          checkLatest: true

      - script: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
        displayName: git config

      # - script: sudo apt-get update
      #   displayName: apt update

      # - script: sudo apt-get install valgrind
      #   displayName: apt install valgrind

      - script: node common/scripts/install-run-rush.js install
        displayName: rush install

      - script: node common/scripts/install-run-rush.js rebuild
        displayName: rush rebuild
        condition: succeeded()

      - script: mkdir $(HELGRIND_RESULTS)

      - script: 'valgrind --tool=helgrind --suppressions=$(Agent.BuildDirectory)/s/common/config/azure-pipelines/helgrind.supp --gen-suppressions=all --trace-children=yes node common/scripts/install-run-rush.js cover |& tee $(HELGRIND_RESULTS)helgrind$(Build.BuildId).txt'
        displayName: "Run Valgrind's datarace detector (helgrind) on core-backend tests"
        failOnStderr: false
        workingDirectory: $(Agent.BuildDirectory)/s/core/backend

      - task: archiveandpublishartifact@0
        inputs:
          rootFolderOrFile: '$(HELGRIND_RESULTS)'
          archiveFolder: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'HelgrindReport-$(Build.BuildId)'

      - task: PythonScript@0
        inputs:
          scriptSource: filepath
          scriptPath: common/config/azure-pipelines/utils/log_valgrind_errors.py
          arguments: '$(HELGRIND_RESULTS)helgrind$(Build.BuildId).txt'